platform :android do
    desc "Build android assemble release"
    lane :build do
            gradle(
                task: 'clean', 
                project_dir: './android/'
            )
            gradle(
              task: 'assemble',
              build_type: 'Release',
              project_dir: './android'
            )
    end
end